#if !defined(ERRORS_H)
#define ERRORS_H

// errors definitions

// fatal start errors
#define	REGISTER_SERVICE_ERROR		100
#define	START_WINSOCK_ERROR			110
#define	ERROR_CREATE_OBJECTS		120
#define	START_OPEN_DIRECTIORY		125

#define	OPEN_DIRECTORY_ERROR_CFG	131
#define	OPEN_DIRECTORY_ERROR_LOG	132
#define	OPEN_DIRECTORY_ERROR_RECV	133
#define	OPEN_DIRECTORY_ERROR_UPDT	134

#define	CTRL_DISP_ERROR				140

#define	COM_INIT_ERROR				150

#define OPEN_XML_ERROR_SYSTEM		160
#define OPEN_XML_ERROR_POINTS		161
#define OPEN_XML_ERROR_OBJECTS		162
#define OPEN_XML_ERROR_JOBS			163

#define COM_XML_ERROR_SYSTEM		170
#define COM_XML_ERROR_POINTS		171
#define COM_XML_ERROR_OBJECTS		172
#define COM_XML_ERRORS_JOBS			173

#define	ERROR_SELF_ID				175
#define	ERROR_NO_POINTS				176
#define	ERROR_SELF_LINK				177
#define	ERROR_SYSTEM_OBJECTS		178

#define	START_LOGGER_ERROR			180

#define	SOCKET_BIND_ERROR			190

#define	EXCEPTION_ERROR				200

#define	INVALID_SESSION				300
#define	INVALID_COMMAND				302
#define	NOT_CONNECTED				304

#define	WRITE_SOCKET_ERROR			306
#define	READ_SOCKET_ERROR			308

#define	ERROR_OBJECT_ID				350
#define	ERROR_POINT_ID				352
#define	ERROR_JOB_ID				353

#define	ERROR_GET_HASH				354
#define	ERROR_GET_FILE				356
#define	ERROR_PUT_FILE				358

#define	SYSTEM_ERROR_OUTOFMEMORY	400

#define	BAD_CHARS_IN_FILENAME		410
#define	FILE_NOT_FOUND				412
#define	ERR_BAD_FILE_STATUS			414

#define	ERROR_READ_FILE				416
#define	ERROR_WRITE_FILE			418

#define	ERR_TIMEOUT					430

#define	ERROR_NOT_IMPLEMENTED		432
#define	ERROR_SERVER_PROTOCOL		434

#define	BAD_DESTINATION_DIR			440
#define	ERROR_COPY_FILE				442

#define	DONT_NEED_OVERWRITE			450

#define	INVALID_TRANSACTION			460
#define	INVALID_TRANSACTION_STATE	462

#define	PATH_NOT_EXIST				470

#define	FIND_FILE_ERROR				480

#define	PROTOCOL_PACKET_CORRUPTED	482

#define	PROGRAMM_TERMINATING		484

#define	SOCKET_DISCONNECTED			486

#define	DELETE_FILE_ERROR			490

#define	FILE_MOVE_POINTER			492

#define	FILE_HASH_MISMATCH			494

#define	INTERNAL_ERROR				496

#endif
